source "https://rubygems.org"

# to publish on github page
gem 'github-pages', group: :jekyll_plugins

# to publich without github page
#gem "jekyll"

gem "webrick", "~> 1.7"

gem 'wdm', '>= 0.1.0' if Gem.win_platform?